version: "3.9"
services:

  corelight-softsensor:
    build:
      context: ./image-files
      network: host
      args:
        - softsensor_version=1.3.6
        - zkg_version=2.9.0
        - suricata_update_version=1.2.2

    # tag the image name to match the softsensor_version variable
    image: local/softsensor-bundle:1.3.6v0.7
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - SYS_NICE
    container_name: softsensor-bundle
    env_file:
      - vars.env
    environment:
      - COMPOSE_PROJECT_NAME=corelight-softsensor
      - CORELIGHT_LICENSE
      - CORELIGHT_SOFTSENSOR_CONF
    hostname: Softsensor-Docker
    restart: unless-stopped
    privileged: true
    stdin_open: true
    tty: true
