version: "3.9"
services:

  corelight-softsensor:
    build:
      context: ./image-files
      args:
        - softsensor_version=1.3.4
        - zkg_version=2.7.0
        - suricata_update_version=1.2.1

    # tag the image name to match the softsensor_version variable
    image: local/softsensor-bundle:1.3.4v0.2
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - SYS_NICE
    container_name: softsensor-bundle
    env_file:
      - vars.env
    environment:
      - COMPOSE_PROJECT_NAME=corelight-softsensor
      - CORELIGHT_LICENSE
      - CORELIGHT_SOFTSENSOR_CONF
    hostname: Softsensor-Docker
    logging:
      driver: "json-file"
    network_mode: "host"
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/corelight
      - /etc/corelight
      - /var/log/suricata
      - /usr/local/etc/suricata
      - /etc/suricata
      - /var/lib/suricata
    stdin_open: true
    tty: true
